kubernetes deployement

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -51,7 +51,7 @@ jobs:
 
           # Attempt to connect to the WSL instance using SSH
           echo "Attempting to connect to WSL via SSH at ${WSL_SSH_URL}:${WSL_SSH_PORT}"
-          sshpass -p "$SSH_PASSWORD" ssh -v -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o UserKnownHostsFile=/dev/null -o "HostKeyAlias=41.226.7.130" -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} exit || echo "SSH connection failed"
+          sshpass  -t -p "$SSH_PASSWORD" ssh -v -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o UserKnownHostsFile=/dev/null -o "HostKeyAlias=41.226.7.130" -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} exit || echo "SSH connection failed"
 
       # Step 3: SSH into WSL and apply Kubernetes configuration
       - name: Establish SSH connection to WSL Docker Desktop and Apply Kubernetes Config
@@ -65,7 +65,7 @@ jobs:
           echo "Connecting to WSL over SSH..."
 
           # SSH into your WSL instance and apply the Kubernetes configuration
-          sshpass -p "$SSH_PASSWORD" ssh -t -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o UserKnownHostsFile=/dev/null -o "HostKeyAlias=41.226.7.130" -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} << EOF
+          sshpass -t -p "$SSH_PASSWORD" ssh -t -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o UserKnownHostsFile=/dev/null -o "HostKeyAlias=41.226.7.130" -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} << EOF
             echo "Connected to WSL and applying Kubernetes config..."
 
             # Set the kubeconfig and apply Kubernetes manifests
