kubernetes deployement

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -36,46 +36,44 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      # Step 1: Set up SSH key for GitHub Actions
-      - name: Set up SSH key for GitHub Actions
-        uses: webfactory/ssh-agent@v0.5.3
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
-      - name: List loaded SSH keys
-        run: ssh-add -l
+      # Step 1: Install sshpass
+      - name: Install sshpass
+        run: sudo apt-get install -y sshpass
 
       # Step 2: Debug SSH connection using Localtunnel URL
       - name: Debug SSH connection to WSL
+        env:
+          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
         run: |
           # The Localtunnel URL you got from the previous command
           WSL_SSH_URL="salty-streets-admire.loca.lt"
           WSL_SSH_PORT="22"  # Default SSH port
-           
+
           # Attempt to connect to the WSL instance using SSH
           echo "Attempting to connect to WSL via SSH at ${WSL_SSH_URL}:${WSL_SSH_PORT}"
-          ssh -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} exit || echo "SSH connection failed"
+          sshpass -p "$SSH_PASSWORD" ssh -v -o StrictHostKeyChecking=no -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} exit || echo "SSH connection failed"
+
       # Step 3: SSH into WSL and apply Kubernetes configuration
       - name: Establish SSH connection to WSL Docker Desktop and Apply Kubernetes Config
+        env:
+          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
         run: |
           # The Localtunnel URL you got from the previous command
           WSL_SSH_URL="salty-streets-admire.loca.lt"
           WSL_SSH_PORT="22"  # Default SSH port
-          
+
           echo "Connecting to WSL over SSH..."
-          
+
           # SSH into your WSL instance and apply the Kubernetes configuration
-          ssh -t -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} << EOF
+          sshpass -p "$SSH_PASSWORD" ssh -t -o StrictHostKeyChecking=no -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} << EOF
             echo "Connected to WSL and applying Kubernetes config..."
 
             # Set the kubeconfig and apply Kubernetes manifests
             export KUBECONFIG=/path/to/kubeconfig.yaml
             kubectl config use-context docker-desktop --kubeconfig=$KUBECONFIG
-            
+
             kubectl apply -f /path/to/kubernetes/deployment.yaml --kubeconfig=$KUBECONFIG
             kubectl apply -f /path/to/kubernetes/service.yaml --kubeconfig=$KUBECONFIG
             kubectl apply -f /path/to/kubernetes/hpa.yaml --kubeconfig=$KUBECONFIG
             kubectl apply -f /path/to/kubernetes/network-policy.yaml --kubeconfig=$KUBECONFIG
           EOF
-
-  
