kubernetes deployement

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -51,8 +51,7 @@ jobs:
            
           # Attempt to connect to the WSL instance using SSH
           echo "Attempting to connect to WSL via SSH at ${WSL_SSH_URL}:${WSL_SSH_PORT}"
-          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} exit || echo "SSH connection failed"
-
+          ssh -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} exit || echo "SSH connection failed"
       # Step 3: SSH into WSL and apply Kubernetes configuration
       - name: Establish SSH connection to WSL Docker Desktop and Apply Kubernetes Config
         run: |
@@ -63,7 +62,7 @@ jobs:
           echo "Connecting to WSL over SSH..."
           
           # SSH into your WSL instance and apply the Kubernetes configuration
-          ssh -t -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i ~/.ssh/id_rsa hamza@${WSL_SSH_URL} -p ${WSL_SSH_PORT} << EOF
+          ssh -t -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -p ${WSL_SSH_PORT} hamza@${WSL_SSH_URL} << EOF
             echo "Connected to WSL and applying Kubernetes config..."
 
             # Set the kubeconfig and apply Kubernetes manifests
